SRC_URI_append_cl-som-imx8 = " \
	file://0000-arm-imx8-cl-som-imx8-add-initial-board-support.patch \
	file://0001-arm-imx8-cl-som-imx8-ddr-mark-mapping-section.patch \
	file://0002-arm-imx8-cl-som-imx8-dts-Update.patch \
	file://0003-arm-imx8-cl-som-imx8-spl-Add-board_fit_config_name_m.patch \
	file://0004-arm-imx8-cl-som-imx8-defconfig-Enable-FIT.patch \
	file://0005-arm-imx8-cl-som-imx8-Memory-addr-tuning.patch \
	file://0006-cl-som-imx8-Set-MODE_HOST-for-the-USB1.patch \
	file://0007-cl-som-imx8-Add-Android-configuration.patch \
	file://0008-cl-som-imx8-Define-the-platform-reset-function.patch \
	file://0009-cl-som-imx8-move-i2c-pad-controlls-to-common.h.patch \
	file://0010-cl-som-imx8-config-i2c-bus-0.patch \
	file://0011-cl-som-imx8-Add-eeprom-support.patch \
	file://0012-cl-som-imx8-Read-FEC-mac-address-from-eeprom.patch \
	file://0013-cl-som-imx8-config-Disable-CONFIG_NXP_TMU.patch \
	file://0014-cl-som-imx8-Set-correct-module-eeprom-bus-address.patch \
	file://0015-cl-som-imx8-Add-ATP-support.patch \
	file://cl-som-imx8_defconfig \
"
