SRC_URI_append_cl-som-imx8 = " \
	file://0000-arm-imx8-cl-som-imx8-00-add-initial-board-support.patch \
	file://0001-arm-imx8-cl-som-imx8-01-add-initial-board-support.patch \
	file://0002-cl-som-imx8-Move-WDOG-to-SPL.patch \
	file://0003-arm-imx8-cl-som-imx8-02-clean-up-memory-init-code.patch \
	file://0004-arm-imx8-cl-som-imx8-ddr-mark-mapping-section.patch \
	file://0005-arm-imx8-cl-som-imx8-dts-Update.patch \
	file://0006-arm-imx8-cl-som-imx8-spl-Add-board_fit_config_name_m.patch \
	file://0007-arm-imx8-cl-som-imx8-defconfig-Enable-FIT.patch \
	file://0008-arm-imx8-cl-som-imx8-Memory-addr-tuning.patch \
	file://0009-cl-som-imx8-Set-MODE_HOST-for-the-USB1.patch \
	file://0010-cl-som-imx8-Add-Android-configuration.patch \
	file://0011-cl-som-imx8-Define-the-platform-reset-function.patch \
	file://cl-som-imx8_defconfig \
"
